- CHANGELOG.md
- src/network.rs
- src/network_adapter.rs
- tests/basic_functionality.rs
- Fixed non-blocking data lost by active waiting.
- Protected from long UDP packets. 
- Added integration tests.
- Updated v0.4.6
> Fixed data lost on Non-Blocking send & protected UDP.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/events.rs
- Fixed a leak memory produced in each timer sending
- The internals of timers uses now the `at` method from `crossbeam-channel 0.5`
> Fixed leak memory. Better timer events

- Cargo.lock
- Cargo.toml
- src/events.rs
Hello @lemunozm ~
As discussed in #20 , I've bump-up 'crossbeam_channel' to `crossbeam`.
Test has been passed, but please let me know if you think it needs more test cases.
> Switch crossbeam_channel(deprecated) to crossbeam

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/engine.rs
- src/resource_id.rs
From: https://github.com/lemunozm/message-io/issues/41
It was not as simple as modifying the `usize` to u64 because `mio` uses an `usize` internally too and the value is clamped by the 32-bits OS poll.
The fix encodes the adapter id and resource type information into the less significant bits instead of the most significant bits to be sure that whatever word size is used in the OS, these values are always encoded into the `ResourceId`.
> Fixed ResourceId for 32bits arch

- src/events.rs
Discussed in https://github.com/lemunozm/message-io/issues/46.
I tried to run rustfmt but ran into some issues with the .rustfmt.toml file. Probably a better idea to wait until that is fixed before merging this.
I also wrote some unit tests to cover some of the common use cases. Would appreciate some extra 👀 on it to make sure I've done it correctly. I'm sure there's a more elegant way of doing this but seems to serve as a solid foundation. Either way, feedback/comments appreciated!
**Discussion points:**
* Should this be named try_recv or try_receive?
* Does the comment look OK?
* I really wanted to avoid copying the instant but was running into multiple mutable borrow issues for self.timers
> Add try_recv() for non-blocking event queue reads

- .rustfmt.toml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- benches/performance.rs
- src/adapters.rs
- src/adapters/web_socket.rs
- src/driver.rs
- src/engine.rs
- src/events.rs
- src/network.rs
- src/remote_addr.rs
- src/transport.rs
- tests/integration.rs
- Implemented `Serialize`/`Deserialize` for `Transport`.
- Implemented `Serialize`/`Deserialize` for `RemoteAddr`.
- Changed `Url` to `String` in `RemoteAddr`.
- Increase the `ToRemoteAddr` support for many types.
> RemoteAddr extensions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- benches/performance.rs
- src/adapters.rs
- src/adapters/framed_tcp.rs
- src/adapters/tcp.rs
- src/adapters/template.rs
- src/adapters/udp.rs
- src/adapters/ws.rs
- src/lib.rs
- src/network/transport.rs
- tests/integration.rs
- *WebSocket* now can returns when send correctly a `SendStatus::MaxPacketSizeExceeded` instead of `ResourceNotFound` if the packet size is exceeded.
- *UDP* has increases the packet size when send.
Now more bytes per packet can be sent if the OS let it.
- Exported some adapter constants dependent.
- `Transport::max_message_size()` now represents the teorical maximum size (see its related docs).
> Fixed sending UDP and WS sending methods for packet limits

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/adapters/ws.rs
- tests/integration.rs
Internal improvement to reduce the WebSocket latency while reading messages.
- The improvement affects all users except windows.
- Reduce the latency by around 40%.
Related issue: https://github.com/snapview/tungstenite-rs/issues/195
> Reduced websocket latency

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- examples/throughput/main.rs
- src/node.rs
Minor API change:
- Updated `NodeListener::for_each` to works fully synchronous. `Send` trait of the event callback parameter has been removed to works fine with objects like `Rc` `Cell` or references. This method no longer returns a `NodeTask`.
- New method `NodeListener::for_each_async` has been added to support the previous behavior of
`for_each`.
- Added `Debug` to `NodeEvent`.
> Split for_each in sync and async modes

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/node.rs
This PR adds a function to handle the library similar to version 0.11. It adds a non-closure synchronized way (based on an event queue) to process the events.
Nevertheless, this easy comes with an increase in latency. In order to get the best performance, is better to use the `for_each` functions.
- Added `NodeListener::enqueue()`
> Added NodeListener::enqueue

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/events.rs
- tests/integration.rs
Reduced some compilation dependencies (around 10-20 less external dependencies depending on the features):
- `url`: Now, only compiled when the `websocket` feature is enabled. 
- Changed `crossbeam` to `crossbeam_channel`: The `crossbeam` was adding the entire suite of crossbeam libraries when only the channel was used. There is a PR https://github.com/lemunozm/message-io/pull/21 doing the opposite, but it seems that targeting the channel part of the `crossbeam` is correct.
> Reduced dependencies

- CHANGELOG.md
- src/node.rs
Although the `NodeHandler` was already clonable. It underlying contained three Arcs. Because the NodeHandler is an entity that in practice can be copied hundred or thousands of times this Arcs quantity has been reduced to one to save more memory and be faster in the clones
> Reduced NodeHandler clone cost

- CHANGELOG.md
- src/network/endpoint.rs
- src/network/transport.rs
- The user can create its own Endpoint with listeners from non-connection oriented transport protocols
> Enabled public endpoint construction. Added example with listeners

- CHANGELOG.md
- benches/latency.rs
- examples/throughput/main.rs
- src/adapters/udp.rs
- src/adapters/ws.rs
- src/network.rs
- src/network/adapter.rs
- src/network/driver.rs
- src/network/transport.rs
- tests/integration.rs
- Modified `SendStatus::MaxPacketSizeExceeded`, now it not contains lengths info.
- Renamed `udp::MAX_COMPATIBLE_PAYLOAD_LEN` to `udp::MAX_LOCAL_PAYLOAD_LEN`, value updatedwith `udp::MAX_PAYLOAD_LEN`.
- Removed `udp::MAX_PAYLOAD_LEN`.- Added `udp::MAX_NETWORK_PAYLOAD_LEN`.
> Send updates

- src/adapters/framed_tcp.rs
- src/node.rs
Sometimes the peer_addr() recovered is set as not connected. Because this method is called only for logging purpose, it can safety removed to avoid connection issues
> Removed peer_addr() call used only for logging purposes

- src/adapters/udp.rs
This change requires all UDP sockets (not just multicast sockets) to be created by socket2::Socket as mio::net::UdpSocket does not provide the set_reuse_address and set_reuse_port functions.
> udp: Add reuse_address and reuse_port options

- Cargo.lock
- Cargo.toml
- src/adapters/udp.rs
On Windows, when listening on a specific IP address, you also receive corresponding subnet broadcasts and global broadcasts (Ipv4Addr::BROADCAST) received on the interface matching the IP.
In order to mimic that behavior on Linux, this change adds ingress filters to UDP/Listen so one can listen on Ipv4Addr::UNSPECIFIED but drop any packet that is not received on the specified interface or any of the specified IP addresses.
@lemunozm  As I said in #142 I'm not sure if that's too much code for a too specific problem to be merged upstream. But I'll leave it here for you to decide.
> Linux: UDP listen: Receive broadcasts (mimic Windows behavior)

- src/adapters/framed_tcp.rs
- src/adapters/tcp.rs
- src/adapters/udp.rs
- src/network.rs
With public members in the config structs the public API breaks each time we're adding new options as the users MUST or MUST NOT add `.. Default::default()` depending on whether they're setting all options or not. So adding new options breaks for those users who use all options.
This change hides the members from the users and replaces access by dedicated setter functions for each option so adding new options does not break API in the future. (This change obviously is an API break in itself.)
> [refactor] config: Use dedicated functions to set options

- src/adapters/tcp.rs
Sorry to bother you again. It turns out my testing was not sufficient and I need an option to bind the listener to a specific interface as well, when I have multiple interfaces in the same (link-local) subnet. Otherwise the Linux kernel tries to send the `TCP SYN/ACK`  on whichever interface was present first even when it received `TCP SYN` on the other interface. :-\ Therefore a TCP connection cannot be established.
> tcp: listener: Add bind_device option

- src/adapters/udp.rs
Fixes a compile error that I ran into today after running `cargo update`, where it complains that `io::IoSliceMut::new(&mut input_buffer)]` doesn't live long enough, so I moved it into its own mutable variable, named "iov" to solve it.
> Fix compile error: Make IOV live longer

- Cargo.lock
- Cargo.toml
Crate:         tungstenite
Version:       0.16.0
Title:         Tungstenite allows remote attackers to cause a denial of service
Date:          2023-09-25
ID:            RUSTSEC-2023-0065
URL:           https://rustsec.org/advisories/RUSTSEC-2023-0065
Solution:      Upgrade to >=0.20.1
> Update tungstenite to 0.20.1 for security update

- Cargo.lock
- Cargo.toml
Since tungstenite 0.22.0, support for url::Url has become an optional feature, which breaks message-io builds. This commit updates tungstenite to versions greater than or equal to 0.22.0 and requires the URL feature to fix builds.
Fixes #173.
> Fix Tungstenite build error caused by the URL feature
