lemunozm/message-io

src/encoding.rs
This PR enabled the encoding module to encode/decode high size messages.
=> Enable message-io for messages greater than  2^15

src/events.rs
Test (and solve?) CI MacOS issue
=> Minnor test change to get MacOS CI works.

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/file-transfer/README.md, examples/file-transfer/common.rs, examples/file-transfer/main.rs, examples/file-transfer/receiver.rs, examples/file-transfer/sender.rs, examples/tcp/server.rs, examples/udp/server.rs, src/encoding.rs, tests/basic_functionality.rs
- Fixed encoding issue when decode several messages in the same data chunk.
- Added `file-transfer` example.
- Added minor encoding test.
=> Release 0.4.5

examples/file-transfer/sender.rs, src/events.rs
Improved internal events error handling to clarify possible errors to the user.
=> Improved internal events error handling

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, benches/performance.rs, examples/distributed/discovery_server.rs, examples/distributed/participant.rs, examples/file-transfer/receiver.rs, examples/file-transfer/sender.rs, examples/multicast/main.rs, examples/readme_example.rs, examples/tcp/client.rs, examples/tcp/server.rs, examples/udp/client.rs, examples/udp/server.rs, src/events.rs, src/network.rs, tests/basic_functionality.rs
=> Network renaming

CHANGELOG.md, src/encoding.rs
Fixed issue https://github.com/lemunozm/message-io/issues/2
=> Fixed decoded issue with messages less than Padding size

CHANGELOG.md, src/adapter.rs, src/adapters/tcp.rs, src/adapters/udp.rs
- Increase the UDP packet size from `1472` to `9188`  (the minimum OS MTU: OSX)
=> Fixed UDP packet size

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, benches/performance.rs, examples/distributed/participant.rs, examples/file-transfer/sender.rs, examples/multicast/main.rs, examples/ping-pong/README.md, examples/ping-pong/client.rs, examples/ping-pong/common.rs, examples/ping-pong/main.rs, examples/ping-pong/server.rs, src/adapter.rs, src/adapters/tcp.rs, src/adapters/template.rs, src/adapters/udp.rs, src/adapters/web_socket.rs, src/driver.rs, src/endpoint.rs, src/engine.rs, src/lib.rs, src/network.rs, src/transport.rs, tests/integration.rs
- connect() returns also local_addr
=> Returned local_addr at connect. Prepare release 0.8

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/ping-pong/client.rs, examples/ping-pong/common.rs, examples/ping-pong/server.rs, src/adapters/web_socket.rs, src/transport.rs, tests/integration.rs
- Fixed `ping-pong` example to work fina in all protocols.
- Protected ws listener for malicious TCP connections.
- Release 0.8.1
=> Proteced ws accept, fixed ping-pong example.

CHANGELOG.md, Cargo.lock, Cargo.toml, benches/performance.rs, src/adapters/tcp.rs, src/adapters/udp.rs, src/adapters/web_socket.rs, src/encoding.rs, src/lib.rs, src/network.rs, tests/integration.rs
- Fixed UDP sending issue (see changelog)
- Fixed TCP encoding issue.
- Fixed WebSocket accept issue.
- Fixed integration test.
- Organized performance tests (not stable yet).
- Added a *burst* test with order check
=> Fixed issues. Release 0.9.1

CHANGELOG.md, benches/performance.rs, src/adapters.rs, src/adapters/web_socket.rs, src/transport.rs, tests/integration.rs
- Enable running test/benchmarks feature based
=> Tests features

CHANGELOG.md, Cargo.lock, Cargo.toml
=> Prepare release 0.10.2

CHANGELOG.md, README.md, examples/distributed/discovery_server.rs, examples/distributed/participant.rs, examples/file-transfer/receiver.rs, examples/file-transfer/sender.rs, examples/multicast/main.rs, examples/ping-pong/client.rs, examples/ping-pong/server.rs, examples/readme_echo_server.rs, src/driver.rs, src/engine.rs, src/network.rs, tests/integration.rs
- Added `RegisterId` of the listener which generates the connection in `AdapterEvent::Added`
and `NetEvent::Connection` events.
=> Modified Connection/Added events with listener info

Cargo.lock, Cargo.toml, src/adapters/framed_tcp.rs, src/encoding.rs
=> Use integer_encoding crate for varint encoding in tcp header

Cargo.toml
Related to https://github.com/lemunozm/message-io/issues/98
=> Websocket depends on tcp feature

.github/workflows/rust.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, src/adapters/ws.rs, src/node.rs
`websocket` feature should enable only websocket without tls
=> websocket without tls

CHANGELOG.md, Cargo.lock, Cargo.toml, src/events.rs
Allow cancel timer events previouslly sent
=> Added cancel timers

CHANGELOG.md, Cargo.lock, Cargo.toml, src/adapters/ws.rs, src/network/driver.rs, src/network/remote_addr.rs, src/network/resource_id.rs, src/network/transport.rs, src/node.rs
=> Updated mio dependency to 0.8

README.md
see https://github.com/badges/shields/issues/8671
=> README.md: Fix build badge

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
=> Prepare release 0.15.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
Fixes https://github.com/lemunozm/message-io/issues/156
=> Prepare release v0.16.0
